/* Automatically generated by generate-command-code.py, do not edit. */

#include "server.h"

/* We have fabulous commands from
 * the fantastic
 * Redis Command Table! */

/********** CLIENT ********************/

/* CLIENT history */
#define CLIENT_History NULL

/* CLIENT tips */
#define CLIENT_tips NULL

/********** PING ********************/

/* PING history */
#define PING_History NULL

/* PING tips */
const char *PING_tips[] = {
"request_policy:all_shards",
"response_policy:all_succeeded",
NULL
};

/* PING argument table */
struct redisCommandArg PING_Args[] = {
{"message",ARG_TYPE_STRING,-1,NULL,NULL,NULL,CMD_ARG_OPTIONAL},
{0}
};

/* Main command table */
struct redisCommand redisCommandTable[] = {
/* connection */
{"client","A container for client connection commands","Depends on subcommand.","2.4.0",CMD_DOC_NONE,NULL,NULL,COMMAND_GROUP_CONNECTION,CLIENT_History,CLIENT_tips,NULL,-2,CMD_SENTINEL,0},
{"ping","Ping the server","O(1)","1.0.0",CMD_DOC_NONE,NULL,NULL,COMMAND_GROUP_CONNECTION,PING_History,PING_tips,pingCommand,-1,CMD_FAST|CMD_SENTINEL,ACL_CATEGORY_CONNECTION,.args=PING_Args},
{0}
};
